### ISSUE TITLE
[Question] Listing the first set of subdirectories in a working directory

### ISSUE THREAD

**Issue by Morsmalleo** [dwyl/listdirs#10]
Is it possible to get/list the first set of subdirectories in a working directory using `listdirs` so we are able to do something with them later on??

So for example let's say we have a working directory stored in a variable like so
```js
var workDir = 'C:/Users/user/just/some/folder/location';
```
Would I be able to list the first set of subdirectories inside this `workDir` and nothing else?? Something like the example below (apologies if the example contains incorrect structure for folder hierarchy)
```bash
<workDir>
├── folder # <— contains more subfolders but don't list them
├── folder2 # <— contains more subfolders but don't list them
├── folder3 # <— contains more subfolders but don't list them
├── folder4 # <— contains more subfolders but don't list them
├── folder5 # <— contains more subfolders but don't list them
├── TestFile.xml
├── TestFile.yml
└── TestFile.txt
```

**Comment by nelsonic** [comment]
Hi @Morsmalleo, 👋 
Yeah, that's the idea. 
But only the directories. 
Let us know how you get on and if you need anything `else`. 👌

**Comment by Morsmalleo** [comment]
> Hi @Morsmalleo, 👋 Yeah, that's the idea. But only the directories. Let us know how you get on and if you need anything `else`. 👌

Awesome, thank you for getting back to me so quickly, yes that's fine I only need it for the first set of subdirs in a working directory 😁
